export enum CATEGORIES {
  MILK = "milk",
  FRUITS = "fruits",
  VEGETABLES = "vegetables",
  JUICE = "juice",
  YOGURT = "yogurt",
  MEAT = "meat",
  CRISPS = "crisps",
  CHOCOLATE = "chocolate",
  ICECREAM = "icecream",
  CROISANT = "croisant",
  SOFT_DRINKS = "soft-drinks",
  COOKIES = "cookies",
  MARSHMALLOW = "marshmallow",
}
